
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-gauchoride
owner: ucsb-cs156
repo_name: proj-gauchoride
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pconrad-patch-8","number":36,"title":"Create versions.md","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/36"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-removeTodos","number":34,"title":"pc - remove TODOs, left over from starter code","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/34"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-sample-backend-pr","number":33,"title":"pc - add javadoc for ApiController.java","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/33"}]
