
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-gauchoride
owner: ucsb-cs156
repo_name: proj-gauchoride
pull_requests: [{"author":{"id":"MDQ6VXNlcjQwNzc1MzY0","is_bot":false,"login":"Aasish-Virjala","name":"Aasish Virjala"},"headRefName":"qa","number":87,"title":"Qa","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/87"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"cal-spike","number":86,"title":"DRAFT pr (do not merge) spike to test sharing cal via service account","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/86"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"me-SMS-SPIKE","number":85,"title":"Me sms spike","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/85"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"me-9am-1-driver-dashboard","number":83,"title":"me-driver dashboard from m23-9am-1","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/83"},{"author":{"id":"U_kgDOBtFRUg","is_bot":false,"login":"Mohamed-Elfouly","name":""},"headRefName":"me-more-driver-info-frontend","number":82,"title":"Additional Driver Information frontend","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/82"}]
