
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156/proj-gauchoride
owner: ucsb-cs156
repo_name: proj-gauchoride
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-m23-9am-3-rider-app-pages","number":73,"title":"Pc m23 9am 3 rider app pages","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/73"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-m23-9am-3-rider-application","number":72,"title":"Pc m23 9am 3 rider application","url":"https://github.com/ucsb-cs156/proj-gauchoride/pull/72"}]
